### ISSUE TITLE
Extra Span in authorlink

### ISSUE THREAD

**Issue by helgatheviking** [ThematicTheme/Thematic#1]
https://code.google.com/p/thematic/issues/detail?id=143

"Found a HTML validation error in thematic_postmeta_authorlink.
There is an extra closing span tag when creating the authorlink when it is not a link.
PS I only saw it because I validated an attachment page and thematic_is_custom_post_type() returns true on  attachment pages. ", -middlesister

i think part of the reason this didn't get fixed, is that gene added on with something more complicated.  let's fix this asap, and tackle the micro-formats in another issue.

**Comment by falcoraptor** [comment]
Agreed. It's such a small thing, so why put it on hold for something bigger.

**Comment by helgatheviking** [comment]
i haven't figured out how to reference properly, but can you check my pull https://github.com/ThematicTheme/Thematic/pull/3 and then go ahead and merge it in if its right.
