### ISSUE TITLE
Title tag for posts page (Frontpage is static)

### ISSUE THREAD

**Issue by mrleemon** [ThematicTheme/Thematic#10]
My site's frontpage is static and a different page is used for posts. The page which has posts is displaying the same title tag as the frontpage, even though I chose to have a different one for this page.

Frontpage: http://test.oscarciutat.com/
Posts page: http://test.oscarciutat.com/blog/

Both pages are titled after the title of the site: TEST TEST. The posts page should display Blog in its title tag.

I'm using WP 3.4.1 with Thematic 1.0.2.1

**Comment by mrleemon** [comment]
In the meantime, I rewrote the thematic_wptitle() filter:

function childtheme_wptitle( $wp_doctitle, $separator, $sep_location ) {
    if ( is_feed() || !thematic_seo() )
        return $wp_doctitle;
    // otherwise... 
    $site_name = get_bloginfo('name' , 'display');

```
if ( is_single() || ( is_home() && !is_front_page() ) || ( is_page() && !is_front_page() ) ) {
  $content = single_post_title('', FALSE);
}
elseif ( is_front_page() ) { 
  $content = get_bloginfo('description', 'display');
}
elseif ( is_page() ) { 
  $content = single_post_title('', FALSE); 
}
elseif ( is_search() ) { 
  $content = __('Search Results for:', 'thematic'); 
  $content .= ' ' . get_search_query();
}
elseif ( is_category() ) {
  $content = __('Category Archives:', 'thematic');
  $content .= ' ' . single_cat_title('', FALSE);;
}
elseif ( is_tag() ) { 
  $content = __('Tag Archives:', 'thematic');
  $content .= ' ' . thematic_tag_query();
}
elseif ( is_404() ) { 
  $content = __('Not Found', 'thematic'); 
}
else { 
  $content = get_bloginfo('description', 'display');
}

if ( get_query_var('paged') ) {
  $content .= ' ' .$separator. ' ';
  $content .= 'Page';
  $content .= ' ';
  $content .= get_query_var('paged');
}

if($content) {
  if ( is_front_page() ) {
      $elements = array(
        'site_name' => $site_name,
        'separator' => $separator,
        'content'   => $content
      );
  }
  else {
      $elements = array(
        'content' => $content
      );
  }  
} else {
  $elements = array(
    'site_name' => $site_name
  );
}

// Filters should return an array
$elements = apply_filters('thematic_doctitle', $elements);

// But if they don't, it won't try to implode
if( is_array($elements) ) {
    $thematic_doctitle = implode(' ', $elements);
} else {
    $thematic_doctitle = $elements;
}

return $thematic_doctitle;
```

}
add_filter('wp_title', 'childtheme_wptitle', 10, 3);

**Comment by helgatheviking** [comment]
@middlesister have any thoughts on this?

**Comment by falcoraptor** [comment]
Hm, I would consider this a feature request and not a bug? The behaviour is exactly the same as previous versions of thematic, nothing in the actual generation of the titles have changed when it was moved to a filter. 

The change to filter was made to enable plugins to modify the site title (and because Theme Review Guidelines required it). I wonder how important it is to have it perfect in thematic itself, aren't more and more people using SEO plugins? They get full control over title tags through them.

That said, it's a minor change and I'm not opposed to putting it in if it makes the life easier for some people

```
    if ( is_single() ) {
      $content = single_post_title('', FALSE);
    }
    elseif ( is_home() || is_front_page() ) { 
      $content = get_bloginfo('description', 'display');
    }
```

becomes

```
    if ( is_single() || ( is_home() && !is_front_page() ) || ( is_page() && !is_front_page() ) ) {
      $content = single_post_title('', FALSE);
    }
    elseif ( is_front_page() ) { 
      $content = get_bloginfo('description', 'display');
    }
```

**Comment by mrleemon** [comment]
And...

```
  if ( is_home() || is_front_page() ) {
      $elements = array(
        'site_name' => $site_name,
        'separator' => $separator,
        'content'   => $content
      );
  }
```

becomes...

```
  if ( is_front_page() ) {
      $elements = array(
        'site_name' => $site_name,
        'separator' => $separator,
        'content'   => $content
      );
  }
```

**Comment by helgatheviking** [comment]
alright.  i'm ok with it then.  if you want finer control, i agree filter wp_title() from the child theme or use an SEO plugin. i don't really want to pretend we're good at SEO too... but this makes sense to me.
