### ISSUE TITLE
Move thematic.js enqueue

### ISSUE THREAD

**Issue by scottnix** [ThematicTheme/Thematic#104]
It looks like the file `thematic.js` deals with the superfish menu only.

Normally you can remove the superfish functionality with

```
function childtheme_remove_superfish(){
    remove_theme_support('thematic_superfish');
 }
add_action('wp_enqueue_scripts','childtheme_remove_superfish', 9);
```

But this does not apply to the `thematic.js` file, would be nice if this could be moved into the `if ( current_theme_supports( 'thematic_superfish' ) )` conditional. 

Currently you can just dequeue the extra js file, but it kind of makes the remove_theme_support functionality obsolete.

**Comment by falcoraptor** [comment]
hm no, at the moment the thematic.js handles all of the menu stuff - including the mobile menu toggle. Would you rather split the file in two with one for the mobile menu and another for the superfish? There are so few lines of code that I felt it unneccessary to create more than one file. Why have two http requests by default?

**Comment by falcoraptor** [comment]
another option is to spit out the superfish js directly in wp_head, but I thought that was a less desirable practice considering browser caching and so on. But again, there are so few lines of code that maybe it doesn't matter so much in this case

**Comment by scottnix** [comment]
Not sure what is the best route, I just wanted to draw attention to using `remove_theme_support('thematic_superfish');` doesn't fully remove the scripts anymore.

In my case, I will always 100% completely remove Superfish, it just took me a few minutes to figure out that thematic.js was still lingering around. I haven't messed with Superfish for a long time now, but it  isn't easy to get working correctly with mobile-first approach to setting up CSS.

**Comment by falcoraptor** [comment]
Take a look at thematic.js and what it does. There is a breakpoint variable set, and superfish only gets instantiated above that breakpoint so it won't interfere with the mobile menu. The more recent versions of superfish includes a destroy method and that gets invoked on resize event.

The breakpoint variable can be changed by filtering the array sent to wp_localize_script so child themes can decide where they want to have it. The default is 600px. If the superfish js isn't enqueued, nothing will happen.

I have yet to find a better alternative to superfish that both adds support for touch screens and includes the ability to tab through the menu links - including the submenus. This is important for accessibility and the biggest reason I chose to keep it.

Why do you remove superfish and what do you use to replace it? If there's something better around I would be happy to include that instead.

**Comment by falcoraptor** [comment]
@scottnix  Would you like to switch to using flexnav instead of superfish?

**Comment by scottnix** [comment]
Keep superfish, it has very heavy usage, so you get all the benefits that go along with it. 

I haven't had time to test out the breakpoint variable you mentioned, I have a hard time having fun while tinkering around with menus, so I keep putting it off, but I eventually will give it another go at tinkering with it. :)

I also still think that using `remove_theme_support('thematic_superfish');` to remove the menu should remove all the corresponding js involved, but it isn't a big deal or anything, it is simple to dequeue it.

**Comment by falcoraptor** [comment]
Since removing the thematic.js file on  `remove_theme_support('thematic_superfish');`  means the mobile menu will break, I'll keep it in for now. 

Yes it means 39 lines of unneccessary code will be loaded, but I think it's the lesser evil compared to having two separate js files resulting in two http requests. Like you said, it is simple to dequeue it if needed. I assume a child theme that dequeues the file will add it's own js for the mobile menu.
