### ISSUE TITLE
add initial-scale=1 to meta viewport tag

### ISSUE THREAD

**Issue by falcoraptor** [ThematicTheme/Thematic#114]
Without the intial-scale value, landscape mode on tablets looks like a zoomed in phone version with sidebar below content instead of using the content-sidebar layout.

But _with_ the inital-scale value, sites using non-responsive legacy-styles will not look right. There is sideways scrolling on tablets in portrait mode. The meta viewport tag should only be used on reponsive sites.

We need to distinguish responsive sites from non-responsive. Using legacy mode check will not work, since an xhtml site should be able to be responsive too. Maybe add a theme support for thematic_responsive or similar?

Should `thematic_reponsive` then  enqueue the main stylesheet too by default? That means child themes that want to only use their own styles will need to de-queue it. But maybe that is preferable. Automatic enqueue for the majority of non-techies, and assuming users with enough know-how to create their own stylesheet will also have the know-how to de-queue the parent.

cc @scottnix @emhr

**Comment by scottnix** [comment]
I haven't looked into meta tags in a while, but if I remember correctly there is something wrong with every variation. I am curious, so I will also look into it too.

I will have to think about the other stuff. In my dream world I vote to drop all backwards compatibility and drop xhtml as even being supported... and uhm...anything else that will attract a higher caliber developer community to get interested in Thematic again.

**Comment by falcoraptor** [comment]
Well dropping backwards support is not happening. Upgrading then could break thousands of sites.

But I hear you on the dev part. I am itching to put in grunt and sass and everything else. But you are using gulp are you not? Pros? Cons?

My ideal is to sassify the main stylesheet and use grunt to generate both expanded and minified stylesheets from that. And I wonder if it would be possible to wait with that until 2.1. If there would be any logical place for any css changes to happen then that is in 2.0, but I really really really want to get this release out the door by now.

But I am not really happy with the stylesheet. That's the one thing that makes me hesitate to launch. I feel it's a mashup and not really structured well. And since responsive styling is a feature of this release I think it just looks stupid to rearrange the code again in the next one.

**Comment by falcoraptor** [comment]
The branch in #115 makes it so that upgrading child themes from 1.0.4 will only need to add

``` php
add_theme_support( 'thematic_html5' );
add_theme_support( 'thematic_responsive' );
```

to their functions.php to use the new features. 

The main stylesheet gets enqueued by default in new installs. Any child theme that wants to roll its own styles will need to de-queue it.

**Comment by falcoraptor** [comment]
hm, thinking more about it, I dislike the #115 approach. Better to educate beginners on how to enqueue the parent styesheet than forcing users to de-enqueue when they want use their own stylesheet. Enqueuing the parent stylesheet seems non-standard to me and could be confusing for the more tech-savvy crowd. Do you agree @scottnix?

WordPress 4.0 is slated for this week, I'd like to get Thematic ready this week or the next. Any remaining glitches can be dealt with in point releases.

**Comment by falcoraptor** [comment]
Done. Child themes still need to enqueue parent stylesheet, meta viewport tag is only added in html5/responsive mode. This assumes html5 sites automatically are responsive, xhtml reponsive sites can use add_theme_support('thematic_meta_viewport').

**Comment by ghost** [comment]
Great enqueue is the way forward.
