### ISSUE TITLE
Theme Check recommendations

### ISSUE THREAD

**Issue by bogh11** [ThematicTheme/Thematic#12]
Hi,

Maybe you already know about this issue, or not, because I see it has not been corrected already, or if it must stay like that you can remove this issue.

I have checked my theme with Theme Check plugin and it shows the following recommendations for thematic:

RECOMMENDED: get_theme_data found in the file functions.php. Deprecated since version 3.4. Use wp_get_theme() instead.
Line 88: $frameworkData = get_theme_data(  get_template_directory() . '/style.css' );
Line 94: $childthemeData = get_theme_data( get_stylesheet_directory() . '/style.css' );
RECOMMENDED: get_current_theme found in the file theme-options.php. Deprecated since version 3.4. Use wp_get_theme() instead.
Line 257: <h2><?php printf( __( '%s Theme Options', 'thematic' ), get_current_theme() ); ?></h2>
Line 334: <label for='thm_legacy_opt'><?php printf( __( '%s Theme Options have been upgraded to an improved format. Remove the legacy options from the database.', 'thematic' ), get_current_theme() ); ?></label>
RECOMMENDED: get_bloginfo(url) was found in the file theme-options.php. Use home_url() instead.
RECOMMENDED: get_bloginfo(stylesheet_directory) was found in the file functions.php. Use get_stylesheet_directory_uri() instead.
RECOMMENDED: get_bloginfo( wpurl ) was found in the file functions.php. Use site_url() instead.

Thanks and good luck further

**Comment by helgatheviking** [comment]
thanks!  we'll look into it.  i was pretty sure get_current_theme() has been deprecated in thematic too.  it uses wp_get_theme for anybody using wordpress 3.4 or greater for the shortcodes anyway, but i guess i missed a few other spots.

**Comment by helgatheviking** [comment]
in the dev branch i have deprecated get_current_theme() in theme-options.php with commit cfbe00c788845d41bf22e8b096102e5b7b5cd0b4

it will exist in the code but for anything using wp 3.4 wp_get_theme will be used.  we'll remove the reference completely eventually.  

i presume the remaining get_bloginfo issues are with your own child theme b/c thematic isn't using get_bloginfo for site urls at all.

**Comment by bogh11** [comment]
Thanks for looking into this.
Good luck!
