### ISSUE TITLE
theme recommendations for custom header, background and editor style

### ISSUE THREAD

**Issue by helgatheviking** [ThematicTheme/Thematic#13]
running theme check:

RECOMMENDED: No reference to add_theme_support( 'custom-header', $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
RECOMMENDED: No reference to add_theme_support( 'custom-background', $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.

should we continue to ignore these?  i'm in favor of leaving them for the distant future... and/or child themes.  thoughts?

**Comment by falcoraptor** [comment]
I say this i definitely child theme territory. Since thematic has neither a header image nor a background color by default there is no need to add it. I vote for example code in the sample child theme that people could uncomment if they want to use.

**Comment by helgatheviking** [comment]
ok, I agree.  do you want to handle that?

**Comment by falcoraptor** [comment]
Sure, I'll see what I can come up with
