### ISSUE TITLE
Estonian translation ready for including in 1.0.3

### ISSUE THREAD

**Issue by petskratt** [ThematicTheme/Thematic#21]
finished Estonian (et) translation on http://translate.thematictheme.com/

now if somebody could get the strings out of "waiting" state I could presumably export the .po and start using it on master branch, thankyouverymany :-)

btw, there was one string with nothing but URL http://themeshaper.com - perhaps a mistake?

**Comment by helgatheviking** [comment]
@middlesister do you have to do anything to combine mos and pos from translate.thematictheme.com into the main file? i think we should send it to Ian for dropping into the repo.

**Comment by falcoraptor** [comment]
yes we have to grab them from glotpress and include them in the repo manually I think. I can do that if you want.

@petskratt Great! Do you have the same username in the forums? I have to assign you as a validator so you can mark the translations as correct. Then you can download the po and mo files and you are good to go. (We will put them in the release too, but you won't need to wait for the release to use them)

**Comment by helgatheviking** [comment]
well he does have to wait for the release, unless he manually upgrades to 1.0.3 from the git tag.  do we have a git tag?  either way, i'd like to wrap up our 1.0.3 release since i'm moving on to Prism.  the only thing left to do is update the mo and po files correct?  can you merge them w/ the rest of the theme?

**Comment by falcoraptor** [comment]
No he can download them from glotpress before the release is out. 

I think that putting in the translation files is the last step left. I'll do a forum post for those who have put translations in but are still needing validating. I can put the files into the repo on friday and tag it so we can send to Ian.

**Comment by helgatheviking** [comment]
what i meant was that the glotpress mo and pos don't help if he isn't using
the appropriate version of thematic... esp considering how we radically
overhauled the strings.

friday sounds great for a 1.0.3 drop!  (just had to double check what today
is... how do i keep losing track of the day!?)  :)

**Comment by falcoraptor** [comment]
ah yes, that's true :)

@petskratt I have made you a validator now so you can go ahead and approve your strings :) In the future, the translations you add will be automatically validated and not go through the waiting stage

**Comment by petskratt** [comment]
@helgatheviking I can get latest from git, no problem - BUT glotpress po export gives me only "validated" translations (which is in most cases a good idea)... and letting me validate fixes that, thanks :-)

yep, I'm apparently @petskratt everywhere (incl twitter, skype)

**Comment by helgatheviking** [comment]
ok cool... i'm still working my brain around translations and making things translation ready.  use your new Validator powers for good!  :)
