### ISSUE TITLE
Bug in Thematic_Content

### ISSUE THREAD

**Issue by scottnix** [ThematicTheme/Thematic#26]
I have never noticed until now, but you have 3 options for content to display, full, excerpt and none. 

The none option doesn't work. Test snippet.

```
// show nothing on post categories
function snix_thematic_content($content) {
    if ( is_category() ) {
        $content= 'none';
    }
    return $content;
}
add_filter('thematic_content', 'snix_thematic_content');
```

If you look in the function thematic_content(), it is there as an option, but produces an error.

Currently is, but doesn't work

```
elseif ( strtolower($thematic_content_length) == 'none') {
}
```

Fixed, works.

```
elseif ( strtolower($thematic_content_length) == 'none') {
    $post= '';
}
```

I didn't submit a pull request because I don't know if this is the best way to fix it, either way it currently isn't working. :P

**Comment by ghost** [comment]
Thanks! I'll look into it toninght.

**Comment by ghost** [comment]
Done
