### ISSUE TITLE
childtheme_override_validate_opt bug

### ISSUE THREAD

**Issue by ghost** [ThematicTheme/Thematic#27]
ref: http://wordpress.org/support/topic/overriding-thematic_validate_opt-needlessly-hard

**Comment by josephting** [comment]
+1 this. I'm having problem overriding validate_opt as well.
The options doesn't save. All the options become empty instead.

And another thing is the function name. I don't know if it's correct that way. I'm still a beginner in using Wordpress Theme Framework.
The function name thematic_thematic_validate_opt() for childtheme override, is that a duplicate typo or it's meant that way? Shouldn't it be thematic_validate_opt() ?

**Comment by ghost** [comment]
Thanks for pointing that out. Should be all good now.
