### ISSUE TITLE
Search bar overflows outside of sidebar if browser minimum font size is higher than 10px

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [ThematicTheme/Thematic#30]
Solution: add input#s{max-width:100%} to stylesheet.
![thematic-sidebar](https://f.cloud.github.com/assets/1062138/64106/7a726840-5e2d-11e2-8e10-f4e63f064612.PNG)

**Comment by falcoraptor** [comment]
Hello and thank you for reporting.
We are doing a complete revamp of the stylesheet for the upcoming 2.0 release. This has been adressed in the new styling.
