### ISSUE TITLE
filters for header, main etc divs

### ISSUE THREAD

**Issue by petskratt** [ThematicTheme/Thematic#33]
Some of the divs in header.php / footer.php have filter callbacks allowing customisation - but some div's are unfiltered. Is there some policy decision... or it would be welcomed if I go through all files, add filters and submit a pull request for inclusion?

e.g 

echo ( apply_filters( 'thematic_open_header',  '<div id="header">' ) );
vs
<div id="main">

also, there seems to be filter to remove wrapper... but not customize it -

if ( apply_filters( 'thematic_open_wrapper', true ) ) 
          echo ( '<div id="wrapper" class="hfeed">' );

is there a policy for using filters that modify content vs true/false toggle filters?

**Comment by ghost** [comment]
There was never an official decision. Most of what you're mentioning here were Chris' and my responses to devs/user requests to make Thematic more flexible.

The boolean filters for the wrapper were introduced to provide the ability to remove the wrapper div if desired. I believe that was back in to 0.9.7.1 days.

Later on the filters on the header and footer divs were provided to allow for converting Thematic's default xhtml doctype to html5 and output native HTML 5 elements. Middlesister's Thematic HTML 5 plugin was the motivator for these filter additions.

Anyone is welcome to review Thematic and suggest changes. Thanks for your interest :)

**Comment by ghost** [comment]
Closing... I think I answered your question if not feel free to continue with the discussion.

**Comment by petskratt** [comment]
yes, sure - safe to close, I'll take some time in near future to create some filters and submit them with pull requests
