### ISSUE TITLE
Remove the index and follow tags from header

### ISSUE THREAD

**Issue by JamesGeiger** [ThematicTheme/Thematic#42]
Props to Scott Nix for this one. The index and follow tags output by Thematic should be removed because it is the browser default.

**Comment by falcoraptor** [comment]
You are referring to `thematic_create_robots()`, right? 

At the moment, thematic uses "index, follow" only on first page of blog page, single posts, pages, attachments and front page. And it will not output any robot meta tag at all if any SEO plugin is detected. 

So what should be removed, the "index, follow" part or the "noindex, follow" one of the others?

**Comment by JamesGeiger** [comment]
Let's see what @scottnix says he is wiser than I

**Comment by ghost** [comment]
I'm not really understanding what you're intending either... The rel nofollow / index is for communicating  with search engines and the like. It has nothing to do with a browser, unless you mean a robot or spider that is crawling (indexing) the site.

**Comment by ghost** [comment]
Hi all,
"index, follow" is the default behaviour of search engine bots: if they don't see any contradictory robots instructions such as "noindex" and/or "nofollow" in the `<meta name="robots" />` tag, bots will index the page and follow its links to other pages. Which means that it is not necessary to bother declaring a `<meta name="robots" />` if its content is just going to be the default "index, follow" instruction.
On the other hand, it is also not worth bothering to remove the tag if it's already there, unless you really need to get rid of 42 characters in your HTML code. If it ain't broke, don't fix it!
My 2 cents!

**Comment by ghost** [comment]
@polnoft Thanks for the input. It's always appreciated. I'm of the same opinion. That said, a review Thematic's default SEO would be nice. 

Any volunteers?

**Comment by JamesGeiger** [comment]
@scottnix would be the man for that. The head of the document is already cluttered. I suggest removing the code that generates it.
