### ISSUE TITLE
implement mobile navigation

### ISSUE THREAD

**Issue by falcoraptor** [ThematicTheme/Thematic#57]
I'd like to see as little js a possible. I am willing to borrow heavily from twentytwelve and twentythirteen for this.

We can probably reserve the suckerfish scripts for the compatibility mode and retire them in html5. 

cc @scottnix @SeamlessThemes @emhr

**Comment by falcoraptor** [comment]
Mobile navigation in progress in https://github.com/middlesister/Thematic/tree/feature/mobile-navigation

It's currently checked out at http://thematicdev.invistruct.com/ so it can be tested on different devices. Currently I switched suckerfish off there, I am looking to conditionally load it or see if there is a smaller lightweight alternative that also provides both touch support for tablets and tab support for accessibility.

Visit the site on a tablet and you see what I mean. Css dropdown menus don't work on touchscreens without some js help.

**Comment by JamesGeiger** [comment]
Suckerfish is indeed kind of bloated...

@middlesister any way we can totally rework the markup to get rid of the .sf and stuff? I would prefer an alternative. I hate the sf class being appended everywhere.
