### ISSUE TITLE
cannot override thematic_validate_opt

### ISSUE THREAD

**Issue by yitwail** [ThematicTheme/Thematic#88]
Since thematic_validate_opt()  in library/extensions/theme-options.php returns a value,
the snippet that tests for childtheme_override_validate_opt() must return the value from childtheme_override_validate_opt() as in the code fragment below: (the only thing that's changed is prepending 'return' to childtheme_override_validate_opt($input);

if (function_exists('childtheme_override_validate_opt')) {
        function thematic_validate_opt($input) {
                return childtheme_override_validate_opt($input);
        }
}

**Comment by falcoraptor** [comment]
Thank you for your clear bug report! 
The fix is committed to the develop branch and will be included in Thematic 2.0
